f = open("database.py", "w")
f.write("from sqlalchemy import create_engine\n")
f.write("from sqlalchemy.ext.declarative import declarative_base\n")
f.write("from sqlalchemy.orm import sessionmaker\n")
f.write("from dotenv import load_dotenv\n")
f.write("import os\n")
f.write("\n")
f.write("load_dotenv()\n")
f.write("\n")
f.write("DATABASE_URL = os.getenv('DATABASE_URL')\n")
f.write("engine = create_engine(DATABASE_URL)\n")
f.write("SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\n")
f.write("Base = declarative_base()\n")
f.write("\n")
f.write("def get_db():\n")
f.write("    db = SessionLocal()\n")
f.write("    try:\n")
f.write("        yield db\n")
f.write("    finally:\n")
f.write("        db.close()\n")
f.close()
print("OK")